### ISSUE TITLE
Certain content in GB Editable (block 3) throws error

### ISSUE THREAD

**Issue by salcode** [ahmadawais/Gutenberg-Boilerplate#19]
Entering the following content in a block of type "GB Editable"

```
## Example Heading

Example paragraph
```

Results in the message

> This block has encountered an error and cannot be previewed.

<img width="703" alt="screenshot 2018-01-20 21 38 29" src="https://user-images.githubusercontent.com/5194588/35190206-4c1c9d60-fe2a-11e7-85ca-0715648d8563.png">

There is a lot of information in the browser console regarding the error, starting with 

> Block validation: Block validation failed because an error occurred while generating block content:

<img width="1264" alt="screenshot 2018-01-20 21 40 41" src="https://user-images.githubusercontent.com/5194588/35190230-96c80d04-fe2a-11e7-8900-bf8cbd01b6f1.png">

Possibly related to #12

**Comment by ahmadawais** [comment]
I can see that.

I'd ask you to use [create-guten-block](https://github.com/ahmadawais/create-guten-block) instead of this boilerplate now — I am going to deprecate this project soon and move all the [new examples](https://github.com/ahmadawais/create-guten-block/tree/master/examples) to that project.
