### ISSUE TITLE
question on import

### ISSUE THREAD

**Issue by robbisy** [ahmadawais/Gutenberg-Boilerplate#21]
Hi ahmad I wonder if it's possible to import a react component in the ESNext block like
I made a react component using 
```
import React from 'react'
import { Component } from 'react' 
...
export default MyComponent;
```
in a component file then I import this component in block.js
using 
`import MyComponent from './component/MyComponent';` ?

**Comment by ahmadawais** [comment]
Hey, @robbisy! 

First of all, I'd ask you to use [create-guten-block](https://github.com/ahmadawais/create-guten-block) instead of this boilerplate now — I am going to deprecate this project.

Then take a look at its [example folder](https://github.com/ahmadawais/create-guten-block/tree/master/examples). You can easily add a component that's published over npm or present in your folder structure inside the `block.js`
