### ISSUE TITLE
Quick question, is there a  reason why things are enqueued in two separate functions?

### ISSUE THREAD

**Issue by jcklpe** [ahmadawais/Gutenberg-Boilerplate#26]
Hello Ahmad. Big fan of your work. I'm a designer learning to develop, and I'm taking a class on Gutenberg block development right now. I figured you might know this. I see people always make their gutenberg blocks by enqueuing the block.js and editor styles in one function and then the frontend stuff in another function. Is there a reason it's done this way? Is that simply how Gutenberg is built? Is it not a requirement but it's done for a technical reason? Is it merely a code style thing?

**Comment by ahmadawais** [comment]
@jcklpe instead of answering your question I'd like to ask you to try create-guten-block https://github.com/ahmadawais/create-guten-block which is the up to date version of this repo. When you do try it, build a demo block and read all the inline documentation I wrote so you can understand why's and what's.

You can enqueue everything in one function if you can put the right amount of checks.

Peace! ✌️

**Comment by jcklpe** [comment]
@ahmadawais thank you! Will do :)
